### ISSUE TITLE
how to run this code

### ISSUE THREAD

**Issue by kartiksinghprajapati** [Krprashant94/Hybrid-Cryptography-on-Cloud#1]
tell whole process what to install and how to run

**Comment by krprashant94** [comment]
1. Install python 
2. Install dependency 
```python
pip install secure
pip install pyserial
```
3. Upload the [Arduino key](https://github.com/Krprashant94/Hybrid-Cryptography-on-Cloud/tree/master/src/key) in your Arduino. (Optional and recommended)
4. Run some [example](https://github.com/Krprashant94/Hybrid-Cryptography-on-Cloud/tree/master/example)

You can improve this repo by adding more example. 
[Source Code](https://github.com/Krprashant94/Hybrid-Cryptography-on-Cloud/tree/master/src/securefile)
